### ISSUE TITLE
Built In OAuth

### ISSUE THREAD

**Issue by ShayBox** [awernick/google-assistant-node#5]
It would be cool if you could include an OAuth client and just input JSON or path to the json file like this package https://www.npmjs.com/package/google-assistant, or even just an example of how to use one of the clients you listed in the example, I cannot figure out how this works.

**Comment by awernick** [comment]
I understand that the OAuth flow is a bit complicated and an example would be a great way to show users how it can be done.

Unfortunately, OAuth can be implemented in many ways and I don't want the end-user to assume that there is only one way to use this package.

Regardless, I will make my best attempt to include an example that will point users in the right direction. In the meantime, please read through the linked resources and choose the Google OAuth flow that best suits your needs.

EDIT:
Also, the package mentioned in the above comment utilizes the `open` package to generate OAuth tokens. This package/flow would not work in a server-side (or embedded) implementation of the Google Assistant since it requires a web browser to generate the tokens.

Not trying to discourage the usage of the other Google Assistant package, but its purpose is different to the implementation of this one.

**Comment by ShayBox** [comment]
Yeah thats why I didn't use that package
And do you know of an oauth package that just lets you input the json directly instead of a path to the json file? The server setup i'm using prevents me from keeping local files private, so I need to put the json in a env variable and send it directly to the oauth package

**Comment by awernick** [comment]
What OAuth flow are you using for your project?

**Comment by ShayBox** [comment]
None yet, I don't know what that means, I looked at both the oauth clients in the example, one of them takes a path to a json file which I can't do, then the other one takes a client id and client secret, but I can't get a client secret anymore, just a json file which contains the client id and other things but not the secret

**Comment by awernick** [comment]
Alright, based on your previous comment, I'm going to assume you want to use the Google Assistant in a server-side application.

Here is some information regarding how to implement the OAuth2 flow for server-side applications:
https://developers.google.com/identity/protocols/OAuth2WebServer

As you will notice, it is very intricate and it requires many steps.

Theoretically, you will want to create a GET endpoint in your web server where you redirect to the Google OAuth sign-in page. After sign-in, Google will redirect back to the specified redirect uri along with the OAuth code needed to generate access tokens.

So, you need three endpoints on your web server:
- Assistant-logic (This is whatever your project is trying to do server-side wise)
- Endpoint that generates Google URLs to sign-in
- An endpoint that Google will redirect back to once a user has signed-in successfully. The request will contain an OAuth code that you can use to generate access tokens.

**Comment by awernick** [comment]
In the event that you are trying to implement a server-side Google Assistant, but you do not require multiple user sign-in (all API calls and data will be linked to a single account), then it might be possible to hard code the access token and refresh token. What information does your JSON file contain?

**Comment by ShayBox** [comment]
![image](https://user-images.githubusercontent.com/9505196/32925612-c26f8010-cb10-11e7-9462-dcdedb89f830.png)
This is what it contains, it's the Service Account Key 
![image](https://user-images.githubusercontent.com/9505196/32925621-d0f1df34-cb10-11e7-837f-4b2e8fcab8cb.png)
And yeah It's just one account, all in a headless server

**Comment by ShayBox** [comment]
I couldn't find an oauth package that takes an api key, but one of them required that json file but as a local file instead of raw json, so I was thinking someone could have something similar to that one that lets you pass in the raw json

**Comment by awernick** [comment]
Since you are using a Service Account Key, you can follow the instructions here:
https://github.com/google/google-api-nodejs-client#using-jwt-service-tokens
The example loads the JSON file and then passes the values to the client constructor, but you can simply hardcode the key-value pairs as you'd like.

I do have to warn that Google does not support service account keys to use the Google Assistant API. The API relies on personal information, and a service account key does not have permissions to many of the features that Google needs to gather information within the Google Assistant.

Your best bet is to generate an access_token and refresh_token using the server-side flow I mentioned previously in a comment. Once you have these tokens, you can hardcode them into an OAuth client like in this example:
https://github.com/google/google-api-nodejs-client#making-authenticated-requests

The above procedure is definitely not the correct way of implementing OAuth, but it's the simplest way to do it for testing purposes.

Another example is the method used for the raspberry pi sample:
https://developers.google.com/assistant/sdk/develop/python/run-sample

This OAuth procedure is easier since the Raspberry Pi has access to a shell. If your project is similar and has access to a terminal shell, then you should try to implement a similar flow.

I hope all of this makes sense. I will close the issue for now since this is very dependent on the use case. If you have any questions, feel free to send me an email and I will attempt to help you in any way that I can.
