### ISSUE TITLE
Unclear Readme + Examples

### ISSUE THREAD

**Issue by dolanmiu** [awernick/google-assistant-node#9]
In the example, it uses `.on()`, whereas on the `README`, it uses `.once()`:

https://github.com/awernick/google-assistant-node/blob/master/ts/examples/pcm-audio.ts#L47-L52

`README`:
```ts
// Assistant is ready to accept audio data. NOTE: .once() is used.
assistant.once('ready', (wstream) => {
  audioData.pipe(wstream);
});
```

Are `on` and `once` interchangeable? 

Or is one preferred over the other?

**Comment by awernick** [comment]
Hi @dolanmiu , please refer to the Node.js documentation to see the differences between `.on` and `.once`:
https://nodejs.org/api/events.html

In short, `.on` fires multiple times, while `.once` gets fired once and then gets removed from the list of event listeners. The `ready` event needs to use `on` since multi-requests to the Assistant API will fire multiple times.
